# Generated by Django 4.0.6 on 2022-07-08 12:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='article',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='blogpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='blog.blogtag'),
        ),
    ]
