# Generated by Django 4.0.6 on 2022-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='sub_heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
